server:
  port: 9999
spring:
  application:
    name: spring-biz-module
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.winbaoxian.module.example.component.security.SecurityPhysicalNamingStrategy
  datasource:
    citymanager:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://testwinbx.mysql.rds.aliyuncs.com:3306/citymanager?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
      username: winbx_test
      password: funcitypt001
      initialSize: 1
      minIdle: 1
      maxActive: 5
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1+1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
logging: 
    com.winbaoxian: debug
security:
  class:
    userDTO: com.winbaoxian.module.security.model.dto.SecurityUserDTO
    userEntity: com.winbaoxian.module.example.model.entity.citymanager.SecurityUserEntity