server:
  port: 9999
spring:
  application:
    name: spring-biz-module
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    citymanager:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://testwinbx.mysql.rds.aliyuncs.com:3306/citymanager?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
      username: winbx_test
      password: funcitypt001
      initialSize: 1
      minIdle: 1
      maxActive: 5
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1+1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      cipherText: vault:v1:Zd7xYEU7kLiUG0THKcFnSjszkEzL67r7MNXYpho1Tu1sEcZZ0nyxOw==
    tob:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://testwinbx.mysql.rds.aliyuncs.com:3306/baoxian2b?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
      username: winbx_test
      password: funcitypt001
      initialSize: 1
      minIdle: 1
      maxActive: 5
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1+1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      cipherText: vault:v1:Zd7xYEU7kLiUG0THKcFnSjszkEzL67r7MNXYpho1Tu1sEcZZ0nyxOw==
  aop:
    proxy-target-class: true
  mvc:
    favicon:
      enabled: false
logging:
  level:
    root: info
    org.apache.shiro: INFO
    com.winbaoxian: debug
    org.springframework: trace
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.winbaoxian.broker.component.log.LogAspect: DEBUG
    org.jasig.cas: trace
winbaoxian:
  vault:
    gateway: https://vault.winbaoxian.cn:8200
    encryptionKey: /serverside-qa/decrypt/car_insure_bid
    authType: token
    authToken: 4f956d8c-b6b0-c2ef-baef-4fa24f76d841
cas:
  server-url-prefix: https://sso.winbaoxian.cn
  server-login-url: https://sso.winbaoxian.cn/login
  server-logout-url: https://sso.winbaoxian.cn/logout
  client-host-url: http://localhost:9999
  logout-redirect-url: http://blog.suiyiwen.com
  use-single-sign-out: true
  authentication-url-ignore-patterns: /favicon.ico, /api/winCas/logout, /static/*
